name = "ip"
type = "webpack"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
compatibility_date = "2021-10-02"
kv_namespaces = [
  { binding = "ASNCACHE", id = "cbf787d8bb584d85bc2bfcaad3f9eab8", preview_id = "cbf787d8bb584d85bc2bfcaad3f9eab8" }
]
