name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - "LICENSE"
      - "README.md"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare node
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install node packages
        run: npm ci --ignore-scripts

      - name: Publish
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
          wranglerVersion: "4.38.0"
