name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - "LICENSE"
      - "README.md"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '1.19.8'
